---
title: "Iris data notebook"
output: html_notebook
---

```{r}
library(tidyverse);
library(dplyr);
library(GGally);
library(MASS);
```


```{r}
head(iris)
table(iris$Species)
#ggpairs(iris)
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Length,y = Petal.Width,color=Species))
ggplot(data=iris) + geom_point(mapping = aes(x=Sepal.Length,y = Sepal.Width,color=Species))
```

```{r}
dim(iris)
```

Test Set
```{r}
iris_test <- sample_n(iris,75);
```

Training Set
```{r}
iris_train <- sample_n(iris,115);
```

Compare sets
```{r}
ggplot(iris_train) + geom_point(mapping = aes(x=Petal.Length,y=Petal.Width,color=Species))

ggplot(iris_test) + geom_point(mapping = aes(x=Petal.Length,y=Petal.Width,color=Species))
```

Fit an LDA model
```{r}
iris_lda_fit <- lda(Species ~ Petal.Length + Petal.Width, data = iris_train)
iris_lda_fit
```

Confusion Martrix
```{r}
table(predict(iris_lda_fit,type="class")$class,data=iris_train$Species)
```

```{r}
iris_train <- mutate(iris_train, prediction = predict(iris_lda_fit,type="class")$class)
```


#KNN for Iris
```{r}
library(class)
iris_test <- sample_n(iris,75)
iris_train <- sample_n(iris,115)
```

```{r}
df_knn <- knn(
  as.matrix(iris_train[ ,c("Petal.Length","Petal.Width")],ncol=2),
  as.matrix(iris_test[ ,c("Petal.Length","Petal.Width")],ncol=2),
  as.matrix(iris_train[,"Species"],ncol=1),k=5)
table(df_knn,iris_test[,"Species"])
```

```{r}
vect_knn <- as.vector(df_knn)
df_result <- mutate(iris_test,knn = as.vector(df_knn))
df_result
```

```{r}
p1 <- ggplot(df_result) + geom_point(mapping = aes(x = Petal.Length,y = Petal.Width,color = Species))
p2 <- ggplot(df_result) + geom_point(mapping = aes(x = Petal.Length,y = Petal.Width,color = knn))
p1
p2
```







